export const BRAND_DATA = [
  { name: "Trek", slug: "trek" },
  { name: "Specialized", slug: "specialized" },
  { name: "Scott", slug: "scott" },
  { name: "Canyon", slug: "canyon" },
  { name: "Giant", slug: "giant" },
  { name: "Orbea", slug: "orbea" },
  { name: "Merida", slug: "merida" },
  { name: "Cannondale", slug: "cannondale" },
  { name: "Cube", slug: "cube" },
  { name: "Felt", slug: "felt" },
  { name: "BMC", slug: "bmc" },
  { name: "Cervélo", slug: "cervelo" },
  { name: "Bianchi", slug: "bianchi" },
  { name: "Norco", slug: "norco" },
  { name: "Haibike", slug: "haibike" },
  { name: "Bulls", slug: "bulls" },
  { name: "Focus", slug: "focus" },
  { name: "Bergamont", slug: "bergamont" },
] as const;
