export const STORE_DATA = [
  {
    slug: "xxl",
    name: "XXL",
    url: "https://www.xxl.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "playwright", baseUrl: "https://www.xxl.no/sykler" },
  },
  {
    slug: "bikester",
    name: "Bikester",
    url: "https://www.bikester.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "cheerio", baseUrl: "https://www.bikester.no/sykkel" },
  },
  {
    slug: "stif",
    name: "Stif",
    url: "https://www.stif.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "cheerio", baseUrl: "https://www.stif.no/sykler" },
  },
  {
    slug: "megasykkel",
    name: "Megasykkel",
    url: "https://www.megasykkel.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "cheerio", baseUrl: "https://www.megasykkel.no/sykkel" },
  },
  {
    slug: "sportamore",
    name: "Sportamore",
    url: "https://www.sportamore.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "playwright", baseUrl: "https://www.sportamore.no/sykkel" },
  },
  {
    slug: "sykkelgrossisten",
    name: "Sykkelgrossisten",
    url: "https://www.sykkelgrossisten.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "cheerio", baseUrl: "https://www.sykkelgrossisten.no" },
  },
  {
    slug: "bikefarm",
    name: "BikeFarm",
    url: "https://www.bikefarm.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "cheerio", baseUrl: "https://www.bikefarm.no/sykler" },
  },
  {
    slug: "fjellsport",
    name: "Fjellsport",
    url: "https://www.fjellsport.no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "playwright", baseUrl: "https://www.fjellsport.no/sykler" },
  },
  {
    slug: "canyon",
    name: "Canyon",
    url: "https://www.canyon.com/en-no",
    logoUrl: null,
    shipsToNorway: true,
    scrapingConfig: { type: "playwright", baseUrl: "https://www.canyon.com/en-no/road-bikes/" },
  },
] as const;
